<?php

namespace HomeBudget\HomeBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    public function queryOwnedBy($user) {

        $query = $this->createQueryBuilder("u")
                ->where('u.user = :user')
                ->setParameter('user', $user);

        return $query;
    }
}
