<?php

namespace HomeBudget\HomeBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpendCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpendCategoryRepository extends EntityRepository
{
    public function queryOwnedBy($user) {

        $query = $this->createQueryBuilder("u")
                ->where('u.user = :user')
                ->orderBy('u.name', 'ASC')
                ->setParameter('user', $user);

        return $query;
    }
}
