<?php

namespace HomeBudget\HomeBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpendRepository extends EntityRepository {

    public function queryOwnedBy($user) {

        $query = $this->createQueryBuilder("u")
                ->where('u.user = :user')
                ->setParameter('user', $user);

        return $query;
    }
    
    public function sortByDate($user){
        
        $expends = $this->getEntityManager()->createQuery(
                        'SELECT e FROM HBBundle:Expend e '
                . 'WHERE e.user = :User ORDER BY e.expendDate DESC')
                ->setParameter("User", $user)
                ->getResult();
        return $expends;
        
    }

}
