<?php

namespace HomeBudget\HomeBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpendCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpendCategoryRepository extends EntityRepository
{
    public function queryOwnedBy($user) {

        $query = $this->createQueryBuilder("u")
                ->where('u.user = :user')
                ->andWhere('u.status = 1')
                ->orderBy('u.name', 'ASC')
                ->setParameter('user', $user);

        return $query;
    }
    
    public function findByUserAndStatus($user){
        
        $exCategories = $this->getEntityManager()->createQuery(
                        'SELECT c FROM HBBundle:ExpendCategory c '
                . 'WHERE c.user = :User AND c.status = 1 ORDER BY c.name ASC')
                ->setParameter("User", $user)
                ->getResult();
        return $exCategories;
        
    }
}
