<?php

namespace HomeBudget\HomeBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IncomeCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeCategoryRepository extends EntityRepository
{
    public function queryOwnedBy($user) {

        $query = $this->createQueryBuilder("i")
                ->where('i.user = :user')
                ->andWhere('i.status = 1')
                ->orderBy('i.name', 'ASC')
                ->setParameter('user', $user);

        return $query;
    }
    public function findByUserAndStatus($user){
        
        $inCategories = $this->getEntityManager()->createQuery(
                        'SELECT c FROM HBBundle:IncomeCategory c '
                . 'WHERE c.user = :User ORDER BY c.name ASC')
                ->setParameter("User", $user)
                ->getResult();
        return $inCategories;
        
    }
}
