<?php

namespace HomeBudget\HomeBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IncomeCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeCategoryRepository extends EntityRepository
{
    public function queryOwnedBy($user) {

        $query = $this->createQueryBuilder("i")
                ->where('i.user = :user')
                ->orderBy('i.name', 'ASC')
                ->setParameter('user', $user);

        return $query;
    }
}
