<?php

namespace HomeBudget\HomeBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeRepository extends EntityRepository
{
    public function sortByDate($user){
        
        $incomes = $this->getEntityManager()->createQuery(
                        'SELECT i FROM HBBundle:Income i '
                . 'WHERE i.user = :User ORDER BY i.incomeDate DESC')
                ->setParameter("User", $user)
                ->getResult();
        return $incomes;
        
    }
}
