<?php

namespace HomeBudget\HomeBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends EntityRepository {

    public function queryOwnedBy($user) {

        $query = $this->createQueryBuilder("u")
                ->where('u.user = :user')
                ->orderBy('u.name', 'ASC')
                ->setParameter('user', $user);

        return $query;
    }
    public function findByUserAndStatus($user){
        
        $types = $this->getEntityManager()->createQuery(
                        'SELECT t FROM HBBundle:Type t '
                . 'WHERE t.user = :User AND t.status = 1 ORDER BY t.name ASC')
                ->setParameter("User", $user)
                ->getResult();
        return $types;
        
    }



}
